//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBook
    {
        public int BookId { get; set; }
        public int ReaderTicketNumber { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime PlannedReturnDate { get; set; }
        public Nullable<System.DateTime> RealReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
